// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Brand struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Cars []*Car `json:"cars"`
}

type Car struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Brand *Brand `json:"brand"`
}

type NewBrand struct {
	Name string `json:"name"`
}

type NewCar struct {
	Name    string `json:"name"`
	BrandID string `json:"brandID"`
}
