// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBrand struct {
	Name string `json:"name"`
}

type NewCar struct {
	Name    string `json:"name"`
	BrandID string `json:"brandID"`
}
